### ISSUE TITLE
Hangfire is not supported

### ISSUE THREAD

**Issue by mnhjftihllr6995** [fs7744/Norns.Urd#30]
On .net 6 
Hangfire 1.7 
Norns.Urd 0.0.4.6

`Could not load file or assembly 'Norns.Urd.DynamicProxy.Generated`

thow error on  Hangfire run job   
``` bash
[11:55:35 WRN] Recurring job 'MyLogWorker' can't be scheduled due to an error and will be retried in 00:00:15.
System.InvalidOperationException: Recurring job can't be scheduled, see inner exception for details.
 ---> Hangfire.Common.JobLoadException: Could not load the job. See inner exception for the details.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Norns.Urd.DynamicProxy.Generated, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
File name: 'Norns.Urd.DynamicProxy.Generated, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadConte
xt, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Hangfire.Common.TypeHelper.AssemblyResolver(String assemblyString)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)

```

**Comment by fs7744** [comment]
该问题应该是 Hangfire 的实现是根据Assembly加载物理dll文件，但 Norns.Urd.DynamicProxy.Generated并未物理dll，Hangfire  如不支持，基于emit 的 动态 aop 也没有办法支持
